[package]
name = "lightbird"
version = "0.1.0"
authors = ["zhanglei.sec <zhanglei.sec@bytedance.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
[lib]
name = "lightbird"
path = "src/lib.rs"
doc = true
[dependencies]
